Repository etalab-ia/piaf-ml, pull requests merged in 2021-07, with the labels that each got.

#128 deployment documentation
  deployment/README.md
Labels: documentation

#129 Merge overlapping answers
  deployment/roles/haystack/files/custom_component.py
  src/evaluation/utils/custom_pipelines.py
  test/samples/squad/duplicate_answers.json
  test/test_eval_retriever_reader.py
  test/test_no_duplicate_answers.py
Labels: bug

#133 Add minimum overlap threshold for contexts and answers.
  clients/cnil/pipelines.yaml
  deployment/roles/haystack/files/custom_component.py
  test/conftest.py
  test/samples/squad/duplicate_answers.json
  test/test_no_duplicate_answers.py
Labels: bug

#132 fix deployment permission
  deployment/roles/haystack/tasks/main.yml
Labels: enhancement

#139 Play with question label
  clients/cnil/pipelines.yaml
  deployment/roles/haystack/files/custom_component.py
Labels: enhancement, piaf-ml

#152 Fix deployement TitleEmbeddingRetriever.
  deployment/roles/haystack/files/custom_component.py
Labels: bug

#114 Fix requirements
  clients/cnil/pipelines.yaml
  clients/crpa/pipelines.yaml
  clients/dila/pipelines.yaml
  deployment/roles/haystack/files/custom_component.py
  requirements.txt
  src/evaluation/config/retriever_reader_eval_squad_config.py
  src/evaluation/utils/TitleEmbeddingRetriever.py
  src/evaluation/utils/custom_pipelines.py
  src/evaluation/utils/utils_eval.py
  test/test_eval_retriever_reader.py
  test/test_no_duplicate_answers.py
Labels: enhancement

#156 adding some question for autocomplete
  clients/crpa/knowledge_base/squad.json
Labels: enhancement
